#!/usr/bin/env python3
"""
Translate README.md from English to Norwegian (Bokmål) and write README.no.md.

Markdown code blocks, inline code, URLs, and HTML tags are preserved as-is
so that the output remains valid Markdown after translation.
"""

import re
import sys
import time

try:
    import translators as ts
except ImportError:
    print("ERROR: 'translators' package not installed. Run: pip install translators")
    sys.exit(1)

SOURCE_FILE = "README.md"
TARGET_FILE = "README.no.md"
SOURCE_LANG = "en"
TARGET_LANG = "no"

# Placeholder format used to hide non-translatable tokens during translation.
PLACEHOLDER = "XPLACEHOLDERX{index}X"
PLACEHOLDER_RE = re.compile(r"XPLACEHOLDERX(\d+)X")

# Patterns for content that must not be translated.
PRESERVE_PATTERNS = [
    # Fenced code blocks  (``` … ```)
    re.compile(r"```[\s\S]*?```", re.MULTILINE),
    # Inline code  (`…`)
    re.compile(r"`[^`\n]+`"),
    # Markdown image syntax  ![alt](url)
    re.compile(r"!\[.*?\]\(.*?\)"),
    # Markdown link syntax  [text](url) — preserve the URL part
    re.compile(r"\[([^\]]*)\]\((https?://[^\)]*)\)"),
    # Bare URLs
    re.compile(r"https?://\S+"),
    # HTML tags
    re.compile(r"<[^>]+>"),
]


def extract_preserved(text: str) -> tuple[str, list[str]]:
    """
    Replace every non-translatable token with a numbered placeholder.
    Returns the modified text and the list of extracted tokens.
    """
    tokens: list[str] = []

    def replacer(match: re.Match) -> str:
        idx = len(tokens)
        tokens.append(match.group(0))
        return PLACEHOLDER.format(index=idx)

    for pattern in PRESERVE_PATTERNS:
        text = pattern.sub(replacer, text)

    return text, tokens


def restore_preserved(text: str, tokens: list[str]) -> str:
    """Substitute placeholders back with their original tokens."""

    def restorer(match: re.Match) -> str:
        return tokens[int(match.group(1))]

    return PLACEHOLDER_RE.sub(restorer, text)


def translate_line(line: str) -> str:
    """
    Translate a single non-empty, non-code line from English to Norwegian.
    Blank lines and lines that consist entirely of a preserved token are
    returned unchanged.
    """
    stripped = line.strip()
    if not stripped:
        return line

    # If the line is *only* a placeholder after stripping, skip translation.
    if PLACEHOLDER_RE.fullmatch(stripped):
        return line

    try:
        translated = ts.translate_text(
            stripped,
            translator="google",
            from_language=SOURCE_LANG,
            to_language=TARGET_LANG,
        )
        # Preserve leading whitespace (e.g. list indentation).
        leading = line[: len(line) - len(line.lstrip())]
        return leading + translated
    except Exception as exc:  # pylint: disable=broad-except
        print(f"  Warning: translation failed for line ({exc!r}), keeping original.")
        return line


def translate_block(block: str) -> str:
    """Translate a paragraph / block of text line by line."""
    lines = block.splitlines(keepends=True)
    result = []
    for line in lines:
        # Small delay to stay within free-tier rate limits.
        time.sleep(0.15)
        result.append(translate_line(line.rstrip("\n")) + ("\n" if line.endswith("\n") else ""))
    return "".join(result)


def main() -> None:
    print(f"Reading {SOURCE_FILE} …")
    with open(SOURCE_FILE, encoding="utf-8") as fh:
        source = fh.read()

    print("Extracting non-translatable tokens …")
    masked, tokens = extract_preserved(source)

    print("Translating …")
    translated_masked = translate_block(masked)

    print("Restoring preserved tokens …")
    translated = restore_preserved(translated_masked, tokens)

    header = (
        "<!-- This file is auto-generated by the GitHub Actions workflow "
        "`.github/workflows/translate-readme.yml`.\n"
        "     To update it, modify `README.md` and push to `main`. -->\n\n"
    )

    output = header + translated

    print(f"Writing {TARGET_FILE} …")
    with open(TARGET_FILE, "w", encoding="utf-8") as fh:
        fh.write(output)

    print("Done.")


if __name__ == "__main__":
    main()
